### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [graphMark/gmark#10]
Could you please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Thanks!

**Comment by webdata** [comment]
Hi! 

Following on this... can you please add a LICENSE to the repo? It is a very interesting work but unfortunately nobody can use it otherwise.

Thanks!

**Comment by mbrukman** [comment]
Looks like this was fixed in https://github.com/gbagan/gmark/commit/935708d36f1fd8ac326c4513ccb3b79365c62d49. Thanks, @gbagan!
